application: awlwidget
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /templates
  static_dir: templates

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /index\.html
  static_files: static/index.html
  upload: static/index.html

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /test
  script: test.py
  
- url: /.*
  script: main.py